- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stderr: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.iterm2:
    ~/.ssh/authorized_keys: ssh/authorized_keys
    ~/.ssh/config: ssh/config
    ~/.ssh/id_ecdsa.pub: ssh/id_ecdsa.pub
    ~/.ssh/id_ed25519.pub: ssh/id_ed25519.pub
    ~/.ssh/id_rsa.pub: ssh/id_rsa.pub
    ~/.ssh/sk_mbp.pub: ssh/sk_mbp.pub
    ~/.ssh/sk_wks.pub: ssh/sk_wks.pub
    ~/.ssh/sk_backup.pub: ssh/sk_backup.pub
    ~/.zlogin:
    ~/.zlogout:
    ~/.zprezto:
    ~/.zpreztorc:
    ~/.zprofile:
    ~/.zshenv:
    ~/.zshrc:

- shell:
  - [git submodule update --init --recursive, Checking submodules]
  - [nerd-fonts/install.sh --link --clean --quiet, Updating fonts]
  -
    command: for dotdir in `find ~ -name '.dotfiles.*'`; do $dotdir/.install -Q; done
    stdout: true
    description: Checking for other dotfiles repo's
