- defaults:
    link:
      create: true
      relink: true
      force: true
    clean:
      force: true
    shell:
      stderr: true

- clean: ['~', '~/.ssh']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore:
    ~/.iterm2:
    ~/.shell/aliases.sh: shell/aliases.sh
    ~/.shell/wsl.sh: shell/wsl.sh
    ~/.ssh/authorized_keys: ssh/authorized_keys
    ~/.ssh/config: ssh/config
    ~/.ssh/id_default.pub: ssh/id_default.pub
    ~/.ssh/id_github.pub: ssh/id_github.pub
    ~/.tmux.conf:
    ~/.zlogin:
    ~/.zlogout:
    ~/.zprezto:
    ~/.zpreztorc:
    ~/.zprofile:
    ~/.zshenv:
    ~/.zshrc:

- shell:
  - [git submodule update --init --recursive, Checking submodules]
  - [./fontinstall.sh, Updating fonts]
  -
    command: for dotdir in `find ~ -name '.dotfiles.*'`; do git -C $dotdir pull -q && $dotdir/.install -Q; done
    stdout: true
    description: Checking for other dotfiles repo's
