- defaults:
    link:
      create: true
      relink: true
      force: true
    clean:
      force: true
    shell:
      stderr: true

- clean: ['~', '~/.ssh']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.iterm2:
    ~/.shell/aliases.sh: shell/aliases.sh
    ~/.shell/wsl.sh: shell/wsl.sh
    ~/.ssh/authorized_keys: ssh/authorized_keys
    ~/.ssh/config: ssh/config
    ~/.ssh/id_bastion.pub: ssh/id_bastion.pub
    ~/.ssh/id_default.pub: ssh/id_default.pub
    ~/.ssh/id_github.pub: ssh/id_github.pub
    ~/.ssh/id_home.pub: ssh/id_home.pub
    ~/.ssh/sk_mbp.pub: ssh/sk_mbp.pub
    ~/.ssh/sk_wks.pub: ssh/sk_wks.pub
    ~/.ssh/sk_backup.pub: ssh/sk_backup.pub
    ~/.zlogin:
    ~/.zlogout:
    ~/.zprezto:
    ~/.zpreztorc:
    ~/.zprofile:
    ~/.zshenv:
    ~/.zshrc:

- shell:
  - [git submodule update --init --recursive, Checking submodules]
  - [nerd-fonts/install.sh --link --clean --quiet, Updating fonts]
  -
    command: for dotdir in `find ~ -name '.dotfiles.*'`; do $dotdir/.install -Q; done
    stdout: true
    description: Checking for other dotfiles repo's
