- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.iterm2:
    ~/.ssh/authorized_keys: ssh/authorized_keys
    ~/.ssh/config: ssh/config
    ~/.ssh/id_ecdsa.pub: ssh/id_ecdsa.pub
    ~/.ssh/id_ed25519.pub: ssh/id_ed25519.pub
    ~/.ssh/id_rsa.pub: ssh/id_rsa.pub
    ~/.zlogin:
    ~/.zlogout:
    ~/.zprezto:
    ~/.zpreztorc:
    ~/.zprofile:
    ~/.zshenv:
    ~/.zshrc:

- shell:
  - [git submodule update --init --recursive --remote --depth 1, Checking submodules]
  - [nerd-fonts/install.sh --link --clean, Updating fonts]