name: Dependabot Auto Merge

on:
  pull_request:

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
